### ISSUE TITLE
Update requirement typer

### ISSUE THREAD

**Issue by impredicative** [paw-lu/dressup#213]
@paw-lu Can this package please urgently receive some basic maintenance? It's causing my build to fail. Apparently it uses and requires a number of very old requirements, one of which is `typer` 0.2.1.

    The user requested click==7.1.2
    typer 0.2.1 depends on click<7.2.0 and >=7.1.1
    black 22.10.0 depends on click>=8.0.0

**Comment by paw-lu** [comment]
Yeah no prob.

Is it cool if we raise the minimum python to 3.8.1? It will make things easier for me.

**Comment by paw-lu** [comment]
I see this is at 3.9 https://github.com/impredicative/irc-rss-feed-bot, so I'm assuming 3.8.1 will be cool

**Comment by paw-lu** [comment]
@impredicative v0.1.2 seems to have made it's way out to PyPI—updated to the latest dependencies available.

**Comment by impredicative** [comment]
@paw-lu Unfortunately it is not installing on Python 3.11. It installed on Python 3.10 though. I get the following error message:

> ERROR: Ignored the following versions that require a different python version: 0.1.2 Requires-Python >=3.8.1,<3.11

**Comment by paw-lu** [comment]
yeah this is by design. some dependencies have not updated to 3.11 yet

**Comment by impredicative** [comment]
I am curious which dependencies don't support Python 3.11 yet.

**Comment by paw-lu** [comment]
Iirc it's pytype, which I don't really leverage much, so I'd be fine removing it to add 3.11 support.

but since 3.11 is still new I'm not going to prioritize it right now, but would accept PRs if it's important to someone!

**Comment by impredicative** [comment]
Overall, `dressup==0.1.1` has an unusually large number of third-party dependencies:

```
click
    # via typer
colorama
    # via
    #   dressup
    #   rich
commonmark
    # via rich
pprintpp
    # via rich
pygments
    # via rich
rich
    # via dressup
toml
    # via dressup
typer
    # via dressup
typing-extensions
    # via rich
```

I count 9. I wonder how many of these are strictly necessary for a Python package that turns "words" into "𝔴𝔬𝔯𝔡𝔰", "🆆🅾🆁🅳🆂", and "𝔀𝓸𝓻𝓭𝓼". I wonder if even 1 of the 9 is strictly necessary.

Also, I think a Python package doesn't need to have command-line functionality as its core feature, but it can be among extras. In fact, it looks to me that it's the console functionality that's creating all the unnecessary complications. Dumping it could fix everything.

I think all I mainly need are the files `translator.toml`, `converter.py`, and `exceptions.py`. We know that Python 3.11 has `tomllib` included, so perhaps I don't need any third-party package at all. A JSON file could've worked well just the same.
